Repository multidadosti-erp/multidadosti-addons, pull requests merged in 2018-09, with the labels that each got.

#411 T1357 - Ao fazer um orcamento, o sistema esta mostrando os Fornecedores.
  block_crm_quotation_for_stage/views/sale_order.xml
Labels: Category: Frontend, Type: Bug

#413 T1476 - Ao consultar uma agenda finalizada, o sistema esta mostrando o horário incorreto
  calendar_event_feedback/i18n/pt_BR.po
  calendar_event_feedback/views/calendar_event.xml
Labels: Category: Frontend, Type: Bug, Version: 11.0

#414 T1551 - Organizar menus de atendimento(Helpdesk)
  helpdesk_phonecall_support/views/helpdesk_phonecall_service.xml
Labels: Category: Frontend, Version: 11.0
