Repository multidadosti-erp/multidadosti-addons, pull requests merged in 2018-07, with the labels that each got.

#394 T0973 - Excluir Campo de Projeto do Lançamento Financeiro
  account_payment_project/__manifest__.py
Labels: Type: Sub-task, Version: 11.0

#396 T0963 - Remover o Módulo: base_product_type_expense e account_company_entry
  base_product_type_expense/__manifest__.py
Labels: Category: Infrastructure, Version: 11.0

#398 T1014 - Erro de Tradução - Acertar Palavra sem Acento
  general_payments/i18n/pt_BR.po
Labels: Category: Frontend, Version: 11.0
