Repository multidadosti-erp/multidadosti-addons, pull requests merged in 2018-08, with the labels that each got.

#405 T1154 - Erro ao finalizar evento de calendario
  calendar_event_timesheet/wizards/calendar_event_finish.py
Labels: Type: Bug, Version: 11.0

#407 T1247 - Ajustar filter_domain na tela de tarefas do projeto
  project_task_set_default_filter/views/project_task.xml
Labels: Type: Bug, Version: 11.0

#408 T1291 - Adicionar 'Favoritos' novamente ao kanban de projetos
  project_kanban_onclick_redirect_project/views/project_project.xml
Labels: Type: Improvement, Version: 11.0

#409 T1302 - Adicionar tag 'noupdate' nos arquivos data
  general_calendar/security/general_calendar.xml
  helpdesk_phonecall_support/data/helpdesk_phonecall_service_tag.xml
  helpdesk_phonecall_support/security/helpdesk_phonecall_service.xml
Labels: Type: Sub-task, Version: 11.0
